name: Check if public key is available on GitHub.

on:
  push:
    branches:
      - master
  # schedule:
  # # 平日朝10時（JST）
  #   - cron: '0 2 * * 1-5'

defaults:
  run:
    working-directory: ./.github/workflows/scripts/

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: pwd
    - run: |
      ls -la
    - run: python github_public_key.py
      env: 
        SLACK_WEBHOOK_URL: ${{ secrets.WebhookUrl }}
        TARGET_FILE: ${{ secrets.TARGET_FILE}}
